INSERT INTO Course VALUES("EDMC1001","Algebra"),
("EDMC1002","Geometry"),
("EDME1103","Content and Pedagogy for Selected Topics in Mathematics"),
("EDPS1003","Psychological Issues in the Classroom"),
("EDTL1020","Introduction to Teaching and Learning"),
("EDCU2013","Introduction To Curriculum Studies"),
("EDEA2305","Action Research for School and Classroom Managers"),
("EDGC2010","Orientation to Guidance and Counselling"),
("EDHE2912","The Nature Of History"),
("EDLA2103","The Teaching Of Literature"),
("EDLA2106","The Language-Structure Content Of English Teaching"),
("EDLS2605","Learner Processes, Teacher Processes & the Development of Literacy"),
("EDMC2201","Introductory Calculus"),
("EDMC2203","Analytical Geometry and Trigonometry"),
("EDMC2214","The Nature and Scope of Mathematics"),
("EDMC2216","Analysis & Teaching of Math"),
("EDME2006","Classroom Testing & Evaluation (Basic)"),
("EDME2202","Probability & Statistics"),
("EDPS2003","Motivation and the Teacher"),
("EDRS2007","Research Design in Education"),
("EDSS2903","Enquiry Methods in Teaching Social Studies"),
("EDSS2904","Practice in Planning Learning Experiences for Social Studies"),
("EDTK2025","Introduction To Computer Technology in Education"),
("EDAR3808","Art and Drama in Education"),
("EDEA3304","Management Of Human Resources & Interpersonal Relations"),
("EDEA3306","School and Classroom Management A"),
("EDEA3308","Principles & Practices of School Finance"),
("EDEA3316","Fieldwork/Practicum (Educational Administration)"),
("EDEA3320","The Study"),
("EDHE3905","Teaching History in Secondary Schools"),
("EDIT3818","Methodologies for Teaching Info Technology & Computer Science"),
("EDIT3822","Instructional Website Design, Development & Integration into Curriculum"),
("EDLA3104","Literature for Children in the Primary School"),
("EDLA3106","Content and Pedagogy for CXC English Language A"),
("EDLA3109","Teaching the Structure of English"),
("EDLS3603","Advanced Study Of Assessment Of Literacy"),
("EDMA3206","Investigations and Problem Solving"),
("EDMC3201","Linear Algebra"),
("EDMC3204","Abstract Algebra"),
("EDRS3019","Report"),
("EDSC3410","Sociology of Science Teaching and Learning"),
("EDSC3417","Introduction To Secondary Science Practicals"),
("EDSS3903","Secondary Schools Social Studies Research and Selection"),
("EDSS3911","Teaching Geography in the Caribbean Classroom"),
("EDTK3004","Educational Technology"),
("EDTL3018","Culminating school-based experience: Clinical Practice"),
("EDTL3020","Pre-Practicum"),
("EDTL3021","Field Study"),
("PHYS3500","Advanced Materials Science Laboratory"),
("EDTL1021","Planning for Teaching and Learning"),
("EDEA2304","Introduction To Educational Administration"),
("EDHE2908","Local and Community Studies"),
("EDIT3017","Issues in Information Technology"),
("EDIT3821","Educational Software Design and Development"),
("EDIT3823","Teaching in a Networked Environment"),
("EDIT3825","Assessing Information Technology"),
("EDLA2105","Language Structure Content Of English Teaching in the Caribbean"),
("EDLS2606","Text, Analysis Of Discourse And The Acquisition Of Literacy"),
("EDLS2607","Research Perspectives in the Study of Literacy"),
("EDMC2213","Children Learning Mathematics"),
("EDME2204","Discrete Mathematics"),
("EDPH2024","Issues and Perspectives in Education"),
("EDSC2407","Teaching Methodologies in Science"),
("EDSE2712","Introduction to the Learner in Difficulty"),
("EDSS2906","Basic Geographic Skills for the Social Studies Teacher"),
("EDEA3305","Special Problems in School Administration"),
("EDEA3307","School and Classroom Management B"),
("PHYS3562","The Physics of Non-Crystalline and Amorphous Materials"),
("EDHE3904","Assessment of Achievement in History"),
("EDHE3908","Selecting Methods & Resources for Instruction in Caribbean and World History"),
("EDLA3103","The Teaching of English Literature in the Secondary School"),
("PHYS3565","Thermodynamics and Kinetics of Materials"),
("EDLA3110","Writing in the Secondary School"),
("EDLA3111","Teaching Caribbean Poetry"),
("PHYS3300","Advanced Practices in Medical Physics"),
("EDLS3612","Writing as Literacy Development in the Primary School"),
("EDMC3020","Calculus II"),
("EDMC3202","Assessing Mathematics Learning"),
("EDME3006","Classroom Testing and Evaluation Advance"),
("EDME3205","Teaching Mathematics in Grades 10 and 11"),
("EDRS3008","Research Methods (II)"),
("ELET3450","Satellite Communication and Navigational Systems"),
("EDSC3403","Assessment in Science Teaching"),
("EDSC3408","Environmental Education"),
("EDSC3411","Science Teaching and the History of Science"),
("EDSS3908","The Role Of Soc. Studies/Geo. In Secondary Education"),
("COMP1126","Intro to Computing I"),
("COMP1127","Intro to Computing II"),
("COMP1161","Object-oriented Programming"),
("COMP1210","Math for Computing"),
("COMP1220","Computing and Society"),
("COMP2201","Discrete Mathematics for Computer Science"),
("COMP2211","Analysis of Algorithms"),
("COMP2120","Digital Logic Design"),
("COMP2140","Software Engineering"),
("COMP2171","Object Technology"),
("COMP2190","Net-Centric Computing"),
("COMP2340","Computer Organisation"),
("COMP3101","Operating Systems"),
("COMP3220","Introduction to Artificial Intelligence"),
("COMP3161","Database Management Systems"),
("COMP3652","Language Processors"),
("COMP3702","Theory of Computation"),
("COMP3801","Real-Time Embedded Systems"),
("COMP3901","Group Project"),
("COMP3911","Internship in Computing I"),
("COMP3912","Internship in Computing II"),
("INFO3105","Computer Systems Administration"),
("INFO3110","Information Systems in Organisations"),
("INFO3155","Computer & Network Security for IT"),
("PHYS3400","Physics in Practice Internship"),
("INFO3170","User Interface Design for IT"),
("INFO3180","Dynamic Web Development II"),
("INFO3435","e-Commerce"),
("SWEN2165","Requirement Engineering"),
("SWEN3130","Software Project Management"),
("SWEN3145","Software Modeling"),
("SWEN3165","Software Testing"),
("SWEN3185","Software Reliability and Formal Methods"),
("SWEN3920","Capstone Project (Software Engineering)"),
("MATH6623","Numerical Methods for Differential Equations"),
("STAT6632","Multivariate Statistical Analysis"),
("STAT6630","Introduction of Stochastic Processes"),
("STAT6631","The Analysis of Time Series"),
("PHYS3701","Advanced Renewable Energy Technology and Solutions"),
("MATH6629","Mechanics of Interacting Particles"),
("MATH6633","A Course in Algebraic Number Theory"),
("MATH6634","A course in the History of Mathematics"),
("MATH6628","Differential Geometry"),
("MATH6622","Differential Equations"),
("MATH6635","Complex Analysis and Applications"),
("ECON1000","Principles of Economics I"),
("ECON1003","Mathematics for Social Sciences I"),
("ECON1004","Mathematics for Social Sciences II"),
("ECON1005","Introduction to Statistics"),
("ECON1012","Principles of Economics II"),
("ECON2000","Intermediate Microeconomics I"),
("ECON2001","Intermediate Microeconomics II"),
("ECON2002","Intermediate Macroeconomics I"),
("ECON2003","Intermediate Macroeconomics II"),
("ECON2005","Social & Economic Accounting"),
("ECON2008","Statistical Methods I"),
("ECON2009","Statistical Methods II"),
("ECON2010","Statistical Computing"),
("ECON2014","Sampling Methods for Business and Social Sciences"),
("ECON2015","Matrix Algebra for Business and Social Sciences"),
("ECON2016","Calculus Social Sciences"),
("ECON2020","Caribbean Economy"),
("ECON2023","International Economic Relations I"),
("ECON2024","International Economic Relations II"),
("ECON2025","Economics of Sport"),
("ECON3003","Game theory"),
("ECON3005","Monetary Theory and Policy"),
("ECON3006","International Trade Theory & Policy"),
("ECON3007","International Finance"),
("ECON3008","History of Economic Thought"),
("ECON3010","Finance & Development"),
("ECON3011","Economics of Financial Institutions"),
("ECON3016","Public Finance I"),
("ECON3030","Selected Topics in Economics"),
("ECON3031","Probability and Distribution Theory for Business & Social Sciences"),
("ECON3032","Statistical Estimation and Inference"),
("ECON3034","Environmental Economics"),
("ECON3037","Operations Research I"),
("ECON3040","Non-Parametric Statistics"),
("ECON3049","Econometrics"),
("ECON3050","Applied Econometrics"),
("ECON3051","Development Economics"),
("ECON3072","Financial Markets"),
("ECON3073","Credit Analysis and Lending"),
("MATH1141","Introductory Linear Algebra & Analytic Geometry"),
("MATH1142","Calculus I"),
("MATH1151","Calculus II"),
("MATH1152","Introduction to Formal Mathematics"),
("MATH2401","Elements of Mathematical Analysis"),
("MATH2410","A First Course in Linear Algebra"),
("MATH2404","Introduction to Probability Theory"),
("MATH2411","Introduction to Abstract Algebra"),
("MATH2403","Multivariable Calculus"),
("MATH2420","Ordinary Differential Equations"),
("MATH3155","Complex Variables"),
("MATH3412","Advanced Linear Algebra"),
("MATH3402","A course on Metric Spaces & Topology"),
("MATH3423","Research Project"),
("STAT3001","Regression Analysis"),
("MATH3403","Some Topics in Functional Analyses"),
("MATH3401","Introduction to the Theory of Integration"),
("MATH3411","Advanced Abstract Algebra"),
("MATH3404","Introduction to Differential Geometry with Maple"),
("STAT3002","Time Series"),
("MATH3414","Selected Topics in Operations Research"),
("MATH3421","Partial Differential Equations"),
("MATH3422","Mathematical Modelling"),
("MATH3424","Numerical Methods"),
("ECNG1000","Electrical Circuits"),
("PHYS1411","Mechanics"),
("PHYS1412","Waves, Optics and Thermodynamics"),
("PHYS1421","Electricity and Magnetism"),
("PHYS1422","Modern Physics"),
("ELNG1101","Physics for Engineers"),
("ELET1500","Electrical Circuit Analysis And Devices"),
("MATH1185","Mathematics for Scientists and Engineers"),
("ELET1405","Practices in Basic Electronics"),
("ECNG1012","Engineering Science and Technology"),
("ECNG1009","Introduction to Programming"),
("MDPH6160","Radiation Biology and Protection"),
("MDPH6150","Biomedical Statistics and Informatics"),
("MDPH6140","Basic Medical Electronics and Instrumentation"),
("MDPH6130","Fundamentals of Radiation Physics and Dosimetry"),
("MDPH6120","Physics of the Human Body"),
("MDPH6110","Anatomy and Physiology for Medical Physicists"),
("MDPH6280","Radiation Safety and Protection"),
("MDPH6270","Radiation Therapy 2: Physics, Equipment and Applications"),
("MDPH6260","Radiation Therapy 1: Physics, Equipment and Applications"),
("MDPH6190","Radiation Biology"),
("MDPH6180","Biomedical Statistics"),
("MDPH6170","Information Technology and Equipment in Radiation Medicine"),
("MDPH6135","Fundamentals of Clinical Radiation Physics and Dosimetry"),
("MDPH6115","Anatomy and Physiology for Clinical Medical Physicists"),
("MDPH6215","Diagnostic Radiology Physics, Equipment and Applications"),
("MDPH6230","Nuclear Medicine: Physics, Equipment and Applications"),
("MDPH6240","Non-Ionization Radiation: Physics, Equipment and Applications"),
("PHYS2396","Computer Applications in Physics"),
("ELET2405","Practices in Electronics Designs 1"),
("ELET2415","Practices in Basic Electronics 2"),
("ELET2460","Signals and Systems"),
("ELET2470","Electric Circuit Analysis"),
("ELET2480","Communication Systems"),
("ELET2410","Analysis and Designs of Analog Circuits"),
("ELET2530","Digital Electronics and Systems"),
("ELET2450","Embedded Systems"),
("ELET2420","Introduction to Semiconductor Devices"),
("PHYS2561","Fundamentals of Materials Science"),
("PHYS2671","Fluid Dynamics"),
("PHYS2296","Physics of the Human Body"),
("PHYS2200","Practices in Medical Physics 1"),
("PHYS2386","Electromagnetism and Optics"),
("PHYS2351","Quantum Mechanics and Nuclear Physics"),
("PHYS2300","General Physics Lab 1"),
("PHYS2600","Fluid Dynamics and Environmental Physics Laboratory"),
("PHYS2500","Materials Science Laboratory 1"),
("ELET2210","Speech Processing"),
("ELET2570","Microprocessors and Computer Architecture"),
("PHYS2000","Fundamentals of Energy Statistics"),
("PHYS2701","Essentials of Renewable Energy Technologies and Solutions"),
("PHYS3000","Energy Information Management"),
("ELET3211","Speech and Language Technology"),
("PHYS3200","General Physics Lab 2");
